language: node_js
sudo: false
node_js:
  - node
  - 11
  - 10
  - 9
  - 8
  - 7
  - 6

cache:
  directories:
    - ~/.npm
    - node_modules

env:
  global:
    - secure: XOINlYZG3DYXq5agQXvkad2MfnOO/+z40fn37RKfNuxNI5veBK7tPRcCIQ998o+NyVTpyd3NZhqkowCxAL8bp4HJ81SesRKQSaXoSzgV7CnloxLxcduiiRJ6lnxFGgCbpqyLxZHWr0mQugcLhs5nhiZ5Dnw6dZxYX/oKKvOomZA=
git:
  depth: 10
  submodules: false

branches:
  only:
    - master

before_install:
  # Use exact Node version.
  - nvm use $TRAVIS_NODE_VERSION

  # Setup package managers.
  - npm i -g npm@latest

script:
  - npm run test

after_success:
  - npm run coverage
