language: node_js
node_js:
  - 0.6
  - 0.8
env:
  - TEST_COMMAND="phantomjs ./test/test.js"
  - TEST_COMMAND="node ./test/test.js"
git:
  depth: 1
branches:
  only:
    - master
script:
  $TEST_COMMAND
